# Generated by Django 5.2.4 on 2025-08-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Categoria de productos', 'verbose_name_plural': 'Categorias de productos'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
